apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-nb
  namespace: sqldb
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-images
          image: 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "nb_25"
          ports:
            - containerPort: 3306