apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-nb
  namespace: sqldb
spec:
  containers:
    - name:   
      image: 
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"
        - name: MYSQL_DATABASE
          value: employees
      ports:
        - containerPort: 3306