apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-nb
  namespace: sqldb
spec:
  containers:
    - name: mysql  
      image: 
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "nb_25"
      ports:
        - containerPort: 3306