apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-nb
  namespace: sqldb
spec:
  containers:
    - name: mysql  
      image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha_mysql-repo:mysql-v5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "nb_25"
      ports:
        - containerPort: 3306