apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs-nb
  namespace: sqldb
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-img
          image: 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "nb_25"
          ports:
            - containerPort: 3306