apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs-nb
  namespace: sqldb
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-img
          image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha_mysql-repo:mysql-v5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "passwors"
          ports:
            - containerPort: 3306