apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-appv2
  namespace: webapp2
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name: python-appv2
        image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha_python-app-repo:application-v2.1
        env:
          - name: DBPWD
            value: mysql
          - name: DBUSER
            value: root
          - name: DBHOST
            value: "mysql-service-nb.sqldb.svc.cluster.local"
          - name: DBPORT
            value: "3306"
          - name: DATABASE
            value: employees
          - name: APP_COLOR
            value: lime
        ports:
        - containerPort: 8080