apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: python-app
        image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha_python-app-repo:v.1.0
        env:
          - name: DBPWD
            value: mysql
          - name: DBUSER
            value: root
          - name: DBHOST
            value: 10.96.74.232
          - name: DBPORT
            value: "3306"
          - name: DATABASE
            value: employees
        ports:
        - containerPort: 8080