apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-appv2
  namespace: employees
  labels:
    app: webapp
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v2
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name:  namitha-python-app-repo
        image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha-python-app-repo:application-v2.2
        env:
          - name: DBPWD
            value: "passwors"
          - name: DBUSER
            value: root
          - name: DBHOST
            value: "mysql-service-nb.sqldb.svc.cluster.local"
          - name: DBPORT
            value: "3306"
        ports:
        - containerPort: 8080