apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: webapp
  labels:
    app: webapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
      - name: python-app
        image: 
        env:
          - name: DBPWD
            value: "nb_25"
          - name: DBUSER
            value: root
          - name: DBHOST
            value: 10.96.74.232
          - name: DBPORT
            value: "3306"
          
        ports:
        - containerPort: 8080