apiVersion: v1
kind: Pod
metadata:
  name: python-app
  namespace: webapp
spec:
  containers:
    - name: python-app
      image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha_python-app-repo:v0.1
             
      env:
        - name: DBPWD
          value: mysql
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql-service-nb.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080