apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  labels:
    app: webapp
    version: v1
spec:
  containers:
    - name: 
      image: 
      env:
        - name: DBPWD
          value: "passwors"
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql-service-nb.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: blue
      ports:
        - containerPort: 8080