apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  labels:
    app: webapp
spec:
  containers:
    - name: python-app
      image: 
             
      env:
        - name: DBPWD
          value: "nb_25"
        - name: DBUSER
          value: root
        - name: DBHOST
          value: 10.96.74.232
        - name: DBPORT
          value: "3306"

      ports:
        - containerPort: 8080