apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: python-app
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: python-app
          image: 499560713632.dkr.ecr.us-east-1.amazonaws.com/namitha_python-app-repo:v0.1
          env:
            - name: DBPSWD
              value: mysql
            - name: DBUSER
              value: namitha
            - name: DBHOST
              value: "new.mysql.host"
            - name: DBPORT
              value: "3306"
          ports:
            - containerPort: 8080