apiVersion: v1
kind: Service
metadata:
  name: python-appv2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30010
  selector:
    app: employees
    version: v2