apiVersion: v1
kind: Service
metadata:
  name: python-service-v2
  namespace: employees
  labels:
    app: webapp
    version: v2
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: webapp
    version: v2