apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: webapp
  labels:
    app: webapp
    version: v1
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: webapp
    version: v1